service: swift-service

provider:
  name: openwhisk
  runtime: swift

functions:
  time:
    handler: time.main
    events:
      - http:
          path: time
          method: get


plugins:
  - serverless-openwhisk
