service: aws-python-simple-http-endpoint
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8

functions:
  currentTime:
    handler: handler.endpoint
    events:
      - httpApi:
          path: /time
          method: get
